---
master_service_names:
  - "etcd3"
  - "kube-apiserver"
  - "kube-controller-manager"
  - "kube-scheduler"
  - "ovn-kubernetes-master"

minion_service_names:
  - "kubelet"
  - "ovn-kubernetes-node"
